package com.flysfo.shorttrips.statemachine;

import com.flysfo.shorttrips.statemachine.easyflow.EventEnum;

/**
 * Created by mattluedke on 2/2/16.
 */
public enum Event implements EventEnum {
  APP_QUIT,
  DRIVER_AND_VEHICLE_ASSOCIATED,
  EXIT_AVI_CHECK_COMPLETE,
  FAILURE,
  GPS_DISABLED,
  GPS_ENABLED,
  INSIDE_BUFFERED_EXIT,
  INSIDE_TAXI_LOOP_EXIT,
  INSIDE_TAXI_WAITING_ZONE,
  LATEST_AVI_AT_ENTRY,
  LATEST_AVI_AT_RE_ENTRY,
  LATEST_AVI_AT_TAXI_LOOP,
  LATEST_CID_IS_ENTRY_CID,
  LATEST_CID_IS_PAYMENT_CID,
  LATEST_CID_IS_RE_ENTRY_CID,
  LOGGED_OUT,
  NOT_INSIDE_BUFFERED_EXIT_AFTER_FAILED_RE_ENTRY_CHECK,
  NOT_INSIDE_TAXI_LOOP_EXIT_AFTER_FAILED_PAYMENT_CHECK_LATEST_AVI_ENTRY_OR_STATUS,
  NOT_INSIDE_TAXI_LOOP_EXIT_AFTER_FAILED_PAYMENT_CHECK_LATEST_AVI_NOT_ENTRY_OR_STATUS,
  NOT_INSIDE_TAXI_WAIT_ZONE_AFTER_FAILED_ENTRY_CHECK,
  OUTSIDE_BUFFERED_EXIT,
  OUTSIDE_SHORT_TRIP_GEOFENCE,
  OUTSIDE_TAXI_WAIT_ZONE,
  TRIP_INVALIDATED,
  TIME_EXPIRED,
  TRIP_STARTED,
  TRIP_VALIDATED
}
